# -*- coding: utf-8 -*-

""" Module répertoriant toutes les constantes partagées """

# Critères de préférences pour un trajet
FASTEST = "FASTEST"
SHORTEST = "SHORTEST"
CHEAPEST = "CHEAPEST"
EASIEST = "EASIEST"
NICEST = "NICEST"
LESS_WALKING = "LESS_WALKING"

# Types de bagages
SUITCASE = "SUITCASE"
BACKPACK = "BACKPACK"
HANDBAG = "HANDBAG"
BULKY = "BULKY"

# Les modes de déplacement possibles
DRIVING_MODE = "driving"
BICYCLING_MODE = "bicycling"
WALKING_MODE = "walking"
TRANSIT_MODE = "transit"

# Forfaits Velib possibles
VELIB_SUBSCRIPTION_30M = "VELIB_SUBSCRIPTION_30M"
VELIB_SUBSCRIPTION_45M = "VELIB_SUBSCRIPTION_45M"
VELIB_TICKETS_30M = "VELIB_TICKETS_30M"
VELIB_NO_SUBSCRIPTION = "VELIB_NO_SUBSCRIPTION"

# Forfaits Autolib possibles
AUTOLIB_PREMIUM = "AUTOLIB_PREMIUM"
AUTOLIB_PRET_A_ROULER = "AUTOLIB_PRET_A_ROULER"
AUTOLIB_FIRST_RENTING_OFFER = "AUTOLIB_FIRST_RENTING_OFFER"

# Forfaits métro possibles
SUBWAY_NAVIGO_SUBSCRIPTION = "SUBWAY_NAVIGO_SUBSCRIPTION"  # Or any other unlimited pass
SUBWAY_TICKETS_BOOK = "SUBWAY_TICKETS_BOOK"
SUBWAY_TICKETS_REDUCED = "SUBWAY_TICKETS_REDUCED"
SUBWAY_NO_TITLE = "SUBWAY_NO_TITLE"